### ISSUE TITLE
utils.GenerateRandomString does not provide expected amount of entropy.

### ISSUE THREAD

**Issue by d1str0** [peterzernia/project#7]
This is a security issue.

When generating a token, you call utils.GenerateRandomString to purportedly generate 32 cryptographically secure random characters. However, your "base64" function is not a proper implementation. Using Go's built in Base64 encoding is much safer.

Your function maps bytes (2^8 bits = 256 possible options) to a possible 63 different characters. This is reducing your entropy from 256 to 63 for each byte. Not only is this misleading to any developer using this function, but it's potentially a security issue if entropy is reduced enough to allow for a brute force attack.

Also, since you are using modulus to map 256 items to 63 items, you are changing the distribution of possibilities in a way that favors the first 4 characters of the mapping. Ie. 0, 1, 2 and 3 are more likely to be chosen than the rest.

To mitigate this, use Go's built in base64 encoding.

**Comment by peterzernia** [comment]
closed with https://github.com/peterzernia/project/commit/5b3542a37c2c98cecbf10bd22e1665c8e9307f15
